Desemcopição de funcional


In [1]:
pip install numpy

                                              0.0/15.8 MB ? eta -:--:--
                                              0.1/15.8 MB 3.6 MB/s eta 0:00:05
                                              0.3/15.8 MB 3.8 MB/s eta 0:00:05
                                              0.3/15.8 MB 3.3 MB/s eta 0:00:05
                                              0.3/15.8 MB 3.3 MB/s eta 0:00:05
                                              0.4/15.8 MB 1.6 MB/s eta 0:00:10
     -                                        0.5/15.8 MB 2.0 MB/s eta 0:00:08
     -                                        0.7/15.8 MB 2.2 MB/s eta 0:00:07
     -                                        0.8/15.8 MB 2.1 MB/s eta 0:00:08
     --                                       0.8/15.8 MB 2.0 MB/s eta 0:00:08
     --                                       0.9/15.8 MB 1.9 MB/s eta 0:00:08
     --                                       1.0/15.8 MB 2.1 MB/s eta 0:00:08
     ---                                      1.2/15.8 MB 2


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install pandas

                                              0.0/11.6 MB ? eta -:--:--
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.5/11.6 MB 15.5 MB/s eta 0:00:01
     -                                        0.


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
import numpy as np

In [29]:
x = np.array([2, 5, 7])
x

array([2, 5, 7])

In [32]:
def quadrado():
    y = x ** 2
    return y

In [33]:
quadrado()

array([ 4, 25, 49])

In [47]:
# Juntando tudo em uma única função
a = np.array([2, 5, 7])

def funcao(a):
    b = a**2
    return b

funcao(a)

array([ 4, 25, 49])

In [48]:
# Função com 3 valores

def value(x, y, z):
    a = funcao(x)
    b = funcao(y)
    c = funcao(z)
    return a + b + c

value(4, 25, 49)

3042

Calculando a área de um retângulo

In [61]:
# a = np.array(float(input('Defina um valor para a área: ')))
# b = np.array(float(input('Defina um valor para a largura: ')))

def area(a, b):
    c = a * b
    return c   

area(a, b)

6.0

In [63]:
def mostrar_area():
    a = float(input('Insira comprimento'))
    b = float(input('insira largura'))
    return area(a, b)

mostrar_area()

4.0

Criando um programa para calcular a soma e a média usando duas funções

In [90]:
lista = [10, 20, 30, 40 ,50]

# Soma da lista
def funcao_soma(a):
    return sum(a)
funcao_soma(lista) 
# Media da soma da lista
def funcao_media(a, b):
    a = funcao_soma(lista) 
    b = len(lista)
    return a / b

funcao_media(a, b)

30.0

In [196]:
lista = [10, 20, 30, 40, 50]
def soma(lista):
    soma = sum(lista)
    return soma


def media(lista):
    soma = soma(lista)
    media = soma / len(lista)
    return media

print(soma(lista))
print(media(lista))


150


UnboundLocalError: cannot access local variable 'soma' where it is not associated with a value

Crie um programa para retornar o valor mínimo, máximo, e a diferença entre máximo e mínimo

In [100]:
a = [10, 20, 30, 40, 50]

def maximo(lista):
    return max(lista)

def minimo(lista):
    return min(lista)

def diferenca(maior, menor):
    return maior - menor

print (maximo(a))
print (minimo(a))
print (diferenca(maximo(a), minimo(a)))



50
10
40


Crie um programa que solicita o salário de um funcionário. 
Após isso, crie uma segunda função para calcular o desconto do funcionário.
Posteriormente, crie uma terceira função para retornor o sálario que o funcionara deverá receber.

ate 2000 com 10% de desconto
2000 até 4800 com 15% de desconto
4800 ate 6000 com 20% de desconto
Acima de 6000 com 30% de desconto

In [195]:

salario = float(input('Digite o valor do seu salário: '))
    

def desconto(salario):
    if salario <= 2000:
        desconto =  salario * 0.1

    elif 2000 < salario <= 4800:
        desconto = salario * 0.15

    elif 4800 < salario <= 6000:
        desconto = salario * 0.2

    else:
        desconto = salario * 0.3
    return desconto

def salario_liquido(salario):
    salario_liquido = salario - desconto(salario) 
    return salario_liquido

print('Desconto: ', desconto(salario))
print('Salario liquido: ', salario_liquido(salario))
    

Desconto:  1200.0
Salario liquido:  4800.0


crie um programa para calcular a area de um circulo, uma função para calcular a área e outra pra classificar a área

area > 100 - grande
area > 50 - medio
else - pequeno

In [140]:
# Definindo a area do circulo
def circulo():
    r = float(input('Defina o raio de um circulo: '))
    pi = 3.1415
    area = pi * r**2
    return area

# Classificando o circulo
def classificar():
    area = circulo()
    if area > 100:
        return print('Circulo grande', area)
    elif area > 50:
        return print('Circulo médio', area)
    else:
        return print('Circulo pequeno', area)

classificar()

Circulo grande 314.15000000000003


Crie um função para multiplicar os valores de duas listas.
A primeira função faz a multplicação e a segunda pegará a primeira e ultilizará um append prdutos = [] para multiplicar os respectivos índices das duas listas

lista 1 = [1, 2, 3, 4]
lista 2 = [5, 6, 7, 8]

In [165]:
lista_1 = [1, 2, 3, 4]
lista_2 = [5, 6, 7, 8]

def multplicar(y, z):
    x = y * z
    return x


def multplicar_lista(lista1, lista2):
    produto = []
    for i in range(len(lista1)):
        produto.append(multplicar(lista1[i], lista2[i]))
    return produto
multplicar_lista(lista_1, lista_2)


[5, 12, 21, 32]

Crie um programa para uma calculadora simples de tal forma que tenha uma função para cadâ operação (-, +, /, *).
Posteriormente, crie uma função para operações que fará as quatros ao mesmo tempo

In [220]:
a = float(input('Defina o valor de A: '))
b = float(input('Defina o valor de B: '))

# Criando as operações
def soma(a, b):
    return a + b
def sub(a, b):
    return a - b
def div(a, b):
    return a / b
def mult(a, b):
    return a * b

def calcular(operacoes):
    resultado = []
    for op, a, b in operacoes:
        if op == '+':
            resultado.append(soma(a, b))
        elif op == '-':
            resultado.append(sub(a, b))
        elif op == '/':
            resultado.append(div(a, b))
        else:
            resultado.append(mult(a, b))
    return resultado

expressao = [('+', a, b), ('-', a, b), ('/', a, b), ('*', a, b)]    
resultado_final = calcular(expressao)
print(resultado_final)


[3.0, -1.0, 0.5, 2.0]
