In [9]:
pip install numpy

                                              0.0/15.8 MB ? eta -:--:--
     ---                                      1.4/15.8 MB 43.6 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.5/15.8 MB 32.7 MB/s eta 0:00:01
     ---                                      1.


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
pip install pandas

                                              0.0/11.6 MB ? eta -:--:--
                                              0.2/11.6 MB 4.6 MB/s eta 0:00:03
     -                                        0.4/11.6 MB 4.0 MB/s eta 0:00:03
     --                                       0.7/11.6 MB 5.0 MB/s eta 0:00:03
     ---                                      1.2/11.6 MB 6.1 MB/s eta 0:00:02
     -----                                    1.7/11.6 MB 7.3 MB/s eta 0:00:02
     -------                                  2.2/11.6 MB 7.8 MB/s eta 0:00:02
     --------                                 2.5/11.6 MB 7.6 MB/s eta 0:00:02
     --------                                 2.6/11.6 MB 7.8 MB/s eta 0:00:02
     --------                                 2.6/11.6 MB 7.8 MB/s eta 0:00:02
     --------                                 2.6/11.6 MB 7.8 MB/s eta 0:00:02
     --------                                 2.6/11.6 MB 7.8 MB/s eta 0:00:02
     --------                                 2.6/11.6 MB 7


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
import numpy as np

In [25]:
import pandas as pd

In [26]:
#Tipos de Arrays, listas
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

tupla = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

df_series = pd.Series(tupla)

In [28]:
df_series

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [22]:
# 01
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# 02
array[3]

4

In [21]:
# 03
array01 = np.array([1, 2, 3, 4, 5])
array02 = np.array([6, 7, 8, 9, 10])

sum_array = array01 + array02
sum_array



array([ 7,  9, 11, 13, 15])

In [38]:
# 04
# É necessário colocar nome da variável dentro e fora das chaves, para printa os números, se não virão em booleanas
array_maiores_5 = array[array > 5]
print(array_maiores_5)
    


[ 6  7  8  9 10]


In [44]:
# 05 - Calcular a média e o desvio padrão de um Numpy array contendo números de 1 a 10
# Colocar o nome da variável antes do .mean sla
print('Média', array.mean())

print('Desvio Padrão', array.std())


Média 5.5
Desvio Padrão 2.8722813232690143


In [46]:
# 06 - Concatenação de 2 arrays de 1 a 5 e de 6 a 10, juntar 2 arrays
arr_concat = np.concatenate([array01, array02])
print('Concatenação')
print(arr_concat)


Concatenação
[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
# 07 
# Arange ele subtraí o 1 pelo 11, 10, 9 , 8... até 2, criando assim um range de 1 a 10
arr1 = np.arange(1, 11)
arr2 = np.arange(10, 0, -1)
resultado = arr1 - arr2

print(resultado)

[-9 -7 -5 -3 -1  1  3  5  7  9]


In [49]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
# 08 - Criando array de ordem decrescente, formato de numpy para ordenar = [::- ou + 'str ou num']

arr1 = np.arange(1, 11)
arr_ordenados = np.sort(arr1)[::-1]

print(arr_ordenados)

[10  9  8  7  6  5  4  3  2  1]


In [59]:
# 09 - vê se possuímos valores duplicados
arr03 = np.array([0, 4, 2, 6, 5, 9, 6])
print(np.unique(arr03).size !=arr03.size)

True


In [60]:
# 10 - slicing do terceiro elemento até o setimo
print(array[2:7])

[3 4 5 6 7]
